### ISSUE TITLE
Image Verification

### ISSUE THREAD

**Issue by lioramilbaum** [openshift/contra-hdsl#70]
Following the issue found by @arilivigni and @robnester-rh, an image verification can address it and expose the error sooner

**Comment by arilivigni** [comment]
It would not have found the issue since this was a bug in OpenShift.   It would just fail like it did in the pipeline with no root cause.

**Comment by robnester-rh** [comment]
This issue wasn't related to the Contra-HDSL, but was instead an issue at the OpenShift level. 

As such, there is no image verification step that would have addressed it. The image in your project's namespace was up to date; it appears that a stale version of a container in another namespace was causing an issue. As such, any image verification of containers in your namespace would have reported that everything was up to date and "good to go".

I am considering an update to the `withHdslPod()` var which, as a by-product, might have avoided this OpenShift issue as it would pull the containers directly from Docker Hub instead of relying on imagestreams in OpenShift.
